config/routes.rb
WhereMyMates::Application.routes.draw do
  root :to => 'main#index'
  get 'orders/:id' => 'main#error'

  get 'auth/:id' => 'sessions#new', :as => 'auth'
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  resources :users, :only => :show
  resource :user, :only => [:edit, :update]
  resources :checkins, :only => [:create, :update]

  match 'teams/:invitation_key/join', to: 'entries#create', :as => 'entry'
  resources :teams, only: [:index, :new, :show, :create] do
    get :embed, :on => :member
    resource :entry, :only => :destroy
  end
end

app/views/layouts/_facebook_jssdk.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=187683721368319";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/layouts/_invite_dialog.html.haml
- if current_user && current_user.part_of?(current_team)
  .modal.hide#invite_modal(tabindex="-1" role="dialog" aria-labelledby="inviteModalLabel" aria-hidden="true")
    .modal-header
      %button(type="button" class="close" data-dismiss="modal" aria-hidden="true") ×
      %h3#inviteModalLabel Invite your mates to see them on the map

    .modal-body
      -#%p Just share this link and they will be added to your team after sign up.
      %p Share this link:
      %p
        = text_field_tag :join_link, entry_url(:invitation_key => current_team.invitation_key), :class => 'join_link'

    .modal-footer
      %button.btn.btn-primary Done

app/views/layouts/_navbar.html.haml
.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    %div{class: (controller_name == "main" ? "container" : "container-fluid" )}
      %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse" href='#')
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to image_tag("logo.png"), root_path, :class => 'brand'
      .nav-collapse{class: (controller_name == "main" ? "container" : "container-fluid" )}
        - if current_user
          %ul.nav
            - if current_user.part_of? current_team
              %li
                %a#invite-menu-link(href='#'){data: {need_popover: need_popover.to_s, placement: "bottom", title: "Invite mates", content: "Now invite your mates to see them on the map", trigger: "manual"}} Invite mates
            - else
              %li= link_to "Create team", new_team_path, :remote => true
          %ul.nav.pull-right
            %li.dropdown
              %a.dropdown-toggle{ data: { toggle: "dropdown" }, href: '#' }
                = current_user.name
                %b.caret
              %ul.dropdown-menu
                %li= link_to "Create new team..", new_team_path, :remote => true
                - current_user.teams.each do |team|
                  %li= link_to team.name, team
                %li= link_to 'Manage teams..', teams_path, :remote => true
                %li.divider
                %li= link_to "Manage accounts..", edit_user_path
                %li= link_to "Sign out", signout_path
        - else
          - unless current_page?(root_path)
            %p.navbar-text.pull-right= link_to(image_tag("connect-foursquare.png", alt: "Login with Foursquare"), auth_path(:foursquare))
            %p.navbar-text.pull-right= link_to(image_tag("facebook_login_button.png", alt: "Login with Facebook"), auth_path(:facebook))
            %p.navbar-text.pull-right= link_to(image_tag("sign-in-with-twitter-gray.png", alt: "Login with Twitter"), auth_path(:twitter))

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "WhereMyMates"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    = favicon_link_tag


  %body{class: (controller_name == "main" ? "" : "fluid" )}
    = render "layouts/facebook_jssdk"
    .l-page

      = render "layouts/navbar"

      .l-page__container
        = yield
        = render "layouts/invite_dialog"

      %footer.l-page__footer.navbar-inverse
        .navbar-inner
          %div{class: (controller_name == "main" ? "container" : "container-fluid" )}
            .copyright
              &copy; #{link_to "Evrone.com", "http://evrone.com", target: "_blank"} 2012 - 2013
    #modals
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"
    = javascript_include_tag "https://maps.google.com/maps/api/js?sensor=true&libraries=geometry&language=en"